# Generated by Django 6.0.6 on 2026-06-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.listing'),
        ),
    ]
