# Generated by Django 6.0.6 on 2026-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_school_order_course_order_level_order_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rder_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
