# Generated by Django 6.0.6 on 2026-07-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_order_rder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rder_id',
            new_name='order_id',
        ),
    ]
